version: "3.7"
services:
  db:
    container_name: perm-container
    image: mysql
    volumes:
      - "./.data/db:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: permcontdb
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
    ports:
      - 3306:3306
